[package]
name = "shuttle-memes"
version = "0.2.0"
edition = "2021"

[dependencies]
askama = "0.12.0"
axum = "0.6.18"
shuttle-axum = "0.25.0"
shuttle-runtime = "0.25.0"
shuttle-static-folder = "0.25.0"
tokio = "1.28.2"
tower-http = { version = "0.4.0", features = ["fs"] }
