[package]
name = "shuttle-memes"
version = "0.2.1"
edition = "2021"

[dependencies]
askama = "0.14"
askama_web = { version = "0.14", features = ["axum-0.8"] }
axum = "0.8"
shuttle-axum = "0.56.0"
shuttle-runtime = "0.56.0"
tokio = "1.28.2"
tower-http = { version = "0.6.2", features = ["fs"] }
