[package]
name = "shuttle-memes"
version = "0.2.1"
edition = "2021"

[dependencies]
askama = "0.12.0"
axum = "0.7.0"
shuttle-axum = "0.48"
shuttle-runtime = "0.48"
tokio = "1.28.2"
tower-http = { version = "0.5.2", features = ["fs"] }
